export const occupations = [
  { name: "Dwarven Apothecarist", race: "Dwarf", weapon: "Cudgel (as Staff)", damage: "1d4", tradeGood: "Steel Vial" },
  { name: "Dwarven Blacksmith", race: "Dwarf", weapon: "Hammer (as Club)", damage: "1d4", tradeGood: "Mithril, 1 oz." },
  { name: "Dwarven Riveter", race: "Dwarf", weapon: "Hammer (as Club)", damage: "1d4", tradeGood: "Mithril, 1 oz." },
  { name: "Dwarven Chestmaker", race: "Dwarf", weapon: "Chisel (as Dagger)", damage: "1d4", tradeGood: "Wood, 10 lbs." },
  { name: "Dwarven Herder", race: "Dwarf", weapon: "Staff", damage: "1d4", tradeGood: "Sow" },
  { name: "Dwarven Miner", race: "Dwarf", weapon: "Pick (as Club)", damage: "1d4", tradeGood: "Lantern" },
  { name: "Dwarven Linkman", race: "Dwarf", weapon: "Pick (as Club)", damage: "1d4", tradeGood: "Lantern" },
  { name: "Dwarven Mushroom Farmer", race: "Dwarf", weapon: "Shovel (as Staff)", damage: "1d4", tradeGood: "Sack" },
  { name: "Dwarven Rat-Catcher", race: "Dwarf", weapon: "Club", damage: "1d4", tradeGood: "Net" },
  { name: "Dwarven Stonemason", race: "Dwarf", weapon: "Hammer (as club)", damage: "1d4", tradeGood: "Fine Stones, 10 lbs." },
  { name: "Dwarven Mason", race: "Dwarf", weapon: "Hammer (as club)", damage: "1d4", tradeGood: "Fine Stones, 10 lbs." },
  { name: "Elven Artisan", race: "Elf", weapon: "Staff", damage: "1d4", tradeGood: "Clay, 1 lbs." },
  { name: "Elven Barrister", race: "Elf", weapon: "Quill (as Dart)", damage: "1d4", tradeGood: "Book" },
  { name: "Elven Chandler", race: "Elf", weapon: "Scissors (as Dagger)", damage: "1d4", tradeGood: "Candles, 20" },
  { name: "Elven Falconer", race: "Elf", weapon: "Dagger", damage: "1d4", tradeGood: "Falcon" },
  { name: "Elven Forester", race: "Elf", weapon: "Staff", damage: "1d4", tradeGood: "Herbs, 1 lbs." },
  { name: "Elven Herbalist", race: "Elf", weapon: "Staff", damage: "1d4", tradeGood: "Herbs, 1 lbs." },
  { name: "Elven Glassblower", race: "Elf", weapon: "Hammer (as Club)", damage: "1d4", tradeGood: "Glass Beads" },
  { name: "Elven Navigator", race: "Elf", weapon: "Bow", damage: "1d6", tradeGood: "Spyglass" },
  { name: "Elven Sage", race: "Elf", weapon: "Dagger", damage: "1d4", tradeGood: "Parchment and Quill Pen" },
  { name: "Elven Scholar", race: "Elf", weapon: "Dagger", damage: "1d4", tradeGood: "Parchment and Quill Pen" },
  { name: "Halfling Chicken Butcher", race: "Halfling", weapon: "Hand Axe", damage: "1d6", tradeGood: "Chicken Meat, 5 lbs." },
  { name: "Halfling Dyer", race: "Halfling", weapon: "Staff", damage: "1d4", tradeGood: "Fabric, 3 yards" },
  { name: "Halfling Tailor", race: "Halfling", weapon: "Staff", damage: "1d4", tradeGood: "Fabric, 3 yards" },
  { name: "Halfling Glovemaker", race: "Halfling", weapon: "Awl (as Dagger)", damage: "1d4", tradeGood: "Gloves, 4 pairs" },
  { name: "Halfling Gypsy", race: "Halfling", weapon: "Sling", damage: "1d4", tradeGood: "Hex Doll" },
  { name: "Halfling Haberdasher", race: "Halfling", weapon: "Scissors (as Dagger)", damage: "1d4", tradeGood: "Fine suits, 3 sets" },
  { name: "Halfling Mariner", race: "Halfling", weapon: "Knife (as Dagger)", damage: "1d4", tradeGood: "Sailcloth, 2 yards" },
  { name: "Halfling Moneylender", race: "Halfling", weapon: "Short Sword", damage: "1d6", tradeGood: "" },
  { name: "Halfling Trader", race: "Halfling", weapon: "Short Sword", damage: "1d6", tradeGood: "" },
  { name: "Halfling Vagrant", race: "Halfling", weapon: "Club", damage: "1d4", tradeGood: "Begging Bowl" },
  { name: "Alchemist", race: "Human", weapon: "Staff", damage: "1d4", tradeGood: "Oil, 1 flask" },
  { name: "Animal Trainer", race: "Human", weapon: "Club", damage: "1d4", tradeGood: "Pony" },
  { name: "Armourer", race: "Human", weapon: "Hammer (as Club)", damage: "1d4", tradeGood: "Iron Helmet" },
  { name: "Astrologer", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "Spyglass" },
  { name: "Barber", race: "Human", weapon: "Razor (as Dagger)", damage: "1d4", tradeGood: "Scissors (as Dagger)" },
  { name: "Beadle", race: "Human", weapon: "Staff", damage: "1d4", tradeGood: "Holy Symbol" },
  { name: "Beekeeper", race: "Human", weapon: "Hammer (as club)", damage: "1d4", tradeGood: "Jar of Honey" },
  { name: "Blacksmith", race: "Human", weapon: "Hammer (as Club)", damage: "1d4", tradeGood: "Steel Tongs" },
  { name: "Butcher", race: "Human", weapon: "Cleaver (as axe)", damage: "1d6", tradeGood: "Side of Beef" },
  { name: "Caravan Guard", race: "Human", weapon: "Short Sword", damage: "1d6", tradeGood: "Linen, 1 Yard" },
  { name: "Cheesemaker", race: "Human", weapon: "Cudgel (as Staff)", damage: "1d4", tradeGood: "Stinky Cheese" },
  { name: "Cobbler", race: "Human", weapon: "Awl (as Dagger)", damage: "1d4", tradeGood: "Shoehorn" },
  { name: "Confidence Artist", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "Quality Cloak" },
  { name: "Cooper", race: "Human", weapon: "Crowbar (as Club)", damage: "1d4", tradeGood: "Barrel" },
  { name: "Costermonger", race: "Human", weapon: "Knife (as Dagger)", damage: "1d4", tradeGood: "Fruit" },
  { name: "Cutpurse", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "Small Chest" },
  { name: "Ditchdigger", race: "Human", weapon: "Shovel (as Staff)", damage: "1d4", tradeGood: "Fine Dirt, 1 lbs." },
  { name: "Farmer Potato", race: "Human", weapon: "Pitchfork (as Spear)", damage: "1d8", tradeGood: "Livestock (see notes)" },
  { name: "Farmer Wheat", race: "Human", weapon: "Pitchfork (as Spear)", damage: "1d8", tradeGood: "Livestock (see notes)" },
  { name: "Farmer Turnip", race: "Human", weapon: "Pitchfork (as Spear)", damage: "1d8", tradeGood: "Livestock (see notes)" },
  { name: "Farmer Corn", race: "Human", weapon: "Pitchfork (as Spear)", damage: "1d8", tradeGood: "Livestock (see notes)" },
  { name: "Farmer Rice", race: "Human", weapon: "Pitchfork (as Spear)", damage: "1d8", tradeGood: "Livestock (see notes)" },
  { name: "Farmer Parsnip", race: "Human", weapon: "Pitchfork (as Spear)", damage: "1d8", tradeGood: "Livestock (see notes)" },
  { name: "Farmer Radish", race: "Human", weapon: "Pitchfork (as Spear)", damage: "1d8", tradeGood: "Livestock (see notes)" },
  { name: "Farmer Rutabaga", race: "Human", weapon: "Pitchfork (as Spear)", damage: "1d8", tradeGood: "Livestock (see notes)" },
  { name: "Fortune Teller", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "Tarot Deck" },
  { name: "Gambler", race: "Human", weapon: "Club", damage: "1d4", tradeGood: "Dice" },
  { name: "Gong Farmer", race: "Human", weapon: "Trowel (as Dagger)", damage: "1d4", tradeGood: "Sack of Night Soil" },
  { name: "Ditcher", race: "Human", weapon: "Shovel (as Staff)", damage: "1d4", tradeGood: "Trowel (as Dagger)" },
  { name: "Grave Digger", race: "Human", weapon: "Shovel (as Staff)", damage: "1d4", tradeGood: "Trowel (as Dagger)" },
  { name: "Guild Beggar", race: "Human", weapon: "Sling", damage: "1d4", tradeGood: "Crutches" },
  { name: "Beggar", race: "Human", weapon: "Sling", damage: "1d4", tradeGood: "Crutches" },
  { name: "Healer", race: "Human", weapon: "Club", damage: "1d4", tradeGood: "Holy Water, 1 Vial" },
  { name: "Herbalist", race: "Human", weapon: "Sling", damage: "1d4", tradeGood: "Herbs, 1 lbs." },
  { name: "Herder", race: "Human", weapon: "Staff", damage: "1d4", tradeGood: "Herding Dog" },
  { name: "Hunter", race: "Human", weapon: "Short Bow", damage: "1d6", tradeGood: "Deer Pelt" },
  { name: "Huntsman", race: "Human", weapon: "Short Bow", damage: "1d6", tradeGood: "Deer Pelt" },
  { name: "Indentured Servant", race: "Human", weapon: "Staff", damage: "1d4", tradeGood: "Locket" },
  { name: "Jester", race: "Human", weapon: "Dart", damage: "1d4", tradeGood: "Silk Cloths" },
  { name: "Jeweler", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "Gem worth 20 gp" },
  { name: "Locksmith", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "Fine Tools" },
  { name: "Mendicant", race: "Human", weapon: "Club", damage: "1d4", tradeGood: "Cheese Dip" },
  { name: "Merchant", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "" },
  { name: "Miller/Baker", race: "Human", weapon: "Club", damage: "1d4", tradeGood: "Flour, 1 lbs." },
  { name: "Minstrel", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "Ukulele" },
  { name: "Noble", race: "Human", weapon: "Longsword", damage: "1d8", tradeGood: "Gold Ring worth 10 gp" },
  { name: "Orphan", race: "Human", weapon: "Club", damage: "1d4", tradeGood: "Rag Doll" },
  { name: "Ostler", race: "Human", weapon: "Staff", damage: "1d4", tradeGood: "Bridle" },
  { name: "Rope Maker", race: "Human", weapon: "Knife (as Dagger)", damage: "1d4", tradeGood: "Rope, 100'" },
  { name: "Scribe", race: "Human", weapon: "Dart", damage: "1d4", tradeGood: "Parchment, 10 sheets" },
  { name: "Shaman", race: "Human", weapon: "Mace", damage: "1d6", tradeGood: "Herbs, 1 lbs." },
  { name: "Slave", race: "Human", weapon: "Club", damage: "1d4", tradeGood: "Strange-looking Rock" },
  { name: "Smuggler", race: "Human", weapon: "Sling", damage: "1d4", tradeGood: "Waterproof Sack" },
  { name: "Squire", race: "Human", weapon: "Longsword", damage: "1d8", tradeGood: "Steel Helmet" },
  { name: "Herald", race: "Human", weapon: "Longsword", damage: "1d8", tradeGood: "Steel Helmet" },
  { name: "Tax Collector", race: "Human", weapon: "Longsword", damage: "1d8", tradeGood: "" },
  { name: "Trapper", race: "Human", weapon: "Sling", damage: "1d4", tradeGood: "Badger Pelt" },
  { name: "Molecatcher", race: "Human", weapon: "Sling", damage: "1d4", tradeGood: "Mole Pelt" },
  { name: "Urchin", race: "Human", weapon: "Stick (as Club)", damage: "1d4", tradeGood: "Begging Bowl" },
  { name: "Wainwright", race: "Human", weapon: "Club", damage: "1d4", tradeGood: "Push Cart (see notes)" },
  { name: "Weaver", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "Fine Suit of Clothes" },
  { name: "Wizard's Apprentice", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "Black Grimoire" },
  { name: "Woodcutter", race: "Human", weapon: "Hand Axe", damage: "1d6", tradeGood: "Bundle of Wood" },
  { name: "Woodmonger", race: "Human", weapon: "Hand Axe", damage: "1d6", tradeGood: "Bundle of Wood" },
  { name: "Wood Seller", race: "Human", weapon: "Hand Axe", damage: "1d6", tradeGood: "Bundle of Wood" },
  { name: "Mercenary", race: "Human", weapon: "Longsword", damage: "1d8", tradeGood: "" },
  { name: "Outlaw", race: "Human", weapon: "Short Sword", damage: "1d6", tradeGood: "" },
  { name: "Soldier", race: "Human", weapon: "Spear", damage: "1d8", tradeGood: "" }
];