export const occupations = [
  { id: 0, name: "Dwarven Apothecarist", race: "Dwarf", weapon: "Cudgel (as Staff)", damage: "1d4", tradeGood: "Steel Vial" },
  { id: 1, name: "Dwarven Blacksmith", race: "Dwarf", weapon: "Hammer (as Club)", damage: "1d4", tradeGood: "Mithril, 1 oz." },
  { id: 2, name: "Dwarven Riveter", race: "Dwarf", weapon: "Hammer (as Club)", damage: "1d4", tradeGood: "Mithril, 1 oz." },
  { id: 3, name: "Dwarven Chestmaker", race: "Dwarf", weapon: "Chisel (as Dagger)", damage: "1d4", tradeGood: "Wood, 10 lbs." },
  { id: 4, name: "Dwarven Herder", race: "Dwarf", weapon: "Staff", damage: "1d4", tradeGood: "Sow" },
  { id: 5, name: "Dwarven Miner", race: "Dwarf", weapon: "Pick (as Club)", damage: "1d4", tradeGood: "Lantern" },
  { id: 6, name: "Dwarven Linkman", race: "Dwarf", weapon: "Pick (as Club)", damage: "1d4", tradeGood: "Lantern" },
  { id: 7, name: "Dwarven Mushroom Farmer", race: "Dwarf", weapon: "Shovel (as Staff)", damage: "1d4", tradeGood: "Sack" },
  { id: 8, name: "Dwarven Rat-Catcher", race: "Dwarf", weapon: "Club", damage: "1d4", tradeGood: "Net" },
  { id: 9, name: "Dwarven Stonemason", race: "Dwarf", weapon: "Hammer (as club)", damage: "1d4", tradeGood: "Fine Stones, 10 lbs." },
  { id: 10, name: "Dwarven Mason", race: "Dwarf", weapon: "Hammer (as club)", damage: "1d4", tradeGood: "Fine Stones, 10 lbs." },
  { id: 11, name: "Elven Artisan", race: "Elf", weapon: "Staff", damage: "1d4", tradeGood: "Clay, 1 lbs." },
  { id: 12, name: "Elven Barrister", race: "Elf", weapon: "Quill (as Dart)", damage: "1d4", tradeGood: "Book" },
  { id: 13, name: "Elven Chandler", race: "Elf", weapon: "Scissors (as Dagger)", damage: "1d4", tradeGood: "Candles, 20" },
  { id: 14, name: "Elven Falconer", race: "Elf", weapon: "Dagger", damage: "1d4", tradeGood: "Falcon" },
  { id: 15, name: "Elven Forester", race: "Elf", weapon: "Staff", damage: "1d4", tradeGood: "Herbs, 1 lbs." },
  { id: 16, name: "Elven Herbalist", race: "Elf", weapon: "Staff", damage: "1d4", tradeGood: "Herbs, 1 lbs." },
  { id: 17, name: "Elven Glassblower", race: "Elf", weapon: "Hammer (as Club)", damage: "1d4", tradeGood: "Glass Beads" },
  { id: 18, name: "Elven Navigator", race: "Elf", weapon: "Bow", damage: "1d6", tradeGood: "Spyglass" },
  { id: 19, name: "Elven Sage", race: "Elf", weapon: "Dagger", damage: "1d4", tradeGood: "Parchment and Quill Pen" },
  { id: 20, name: "Elven Scholar", race: "Elf", weapon: "Dagger", damage: "1d4", tradeGood: "Parchment and Quill Pen" },
  { id: 21, name: "Halfling Chicken Butcher", race: "Halfling", weapon: "Hand Axe", damage: "1d6", tradeGood: "Chicken Meat, 5 lbs." },
  { id: 22, name: "Halfling Dyer", race: "Halfling", weapon: "Staff", damage: "1d4", tradeGood: "Fabric, 3 yards" },
  { id: 23, name: "Halfling Tailor", race: "Halfling", weapon: "Staff", damage: "1d4", tradeGood: "Fabric, 3 yards" },
  { id: 24, name: "Halfling Glovemaker", race: "Halfling", weapon: "Awl (as Dagger)", damage: "1d4", tradeGood: "Gloves, 4 pairs" },
  { id: 25, name: "Halfling Gypsy", race: "Halfling", weapon: "Sling", damage: "1d4", tradeGood: "Hex Doll" },
  { id: 26, name: "Halfling Haberdasher", race: "Halfling", weapon: "Scissors (as Dagger)", damage: "1d4", tradeGood: "Fine suits, 3 sets" },
  { id: 27, name: "Halfling Mariner", race: "Halfling", weapon: "Knife (as Dagger)", damage: "1d4", tradeGood: "Sailcloth, 2 yards" },
  { id: 28, name: "Halfling Moneylender", race: "Halfling", weapon: "Short Sword", damage: "1d6", tradeGood: "" },
  { id: 29, name: "Halfling Trader", race: "Halfling", weapon: "Short Sword", damage: "1d6", tradeGood: "" },
  { id: 30, name: "Halfling Vagrant", race: "Halfling", weapon: "Club", damage: "1d4", tradeGood: "Begging Bowl" },
  { id: 31, name: "Alchemist", race: "Human", weapon: "Staff", damage: "1d4", tradeGood: "Oil, 1 flask" },
  { id: 32, name: "Animal Trainer", race: "Human", weapon: "Club", damage: "1d4", tradeGood: "Pony" },
  { id: 33, name: "Armourer", race: "Human", weapon: "Hammer (as Club)", damage: "1d4", tradeGood: "Iron Helmet" },
  { id: 34, name: "Astrologer", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "Spyglass" },
  { id: 35, name: "Barber", race: "Human", weapon: "Razor (as Dagger)", damage: "1d4", tradeGood: "Scissors (as Dagger)" },
  { id: 36, name: "Beadle", race: "Human", weapon: "Staff", damage: "1d4", tradeGood: "Holy Symbol" },
  { id: 37, name: "Beekeeper", race: "Human", weapon: "Hammer (as club)", damage: "1d4", tradeGood: "Jar of Honey" },
  { id: 38, name: "Blacksmith", race: "Human", weapon: "Hammer (as Club)", damage: "1d4", tradeGood: "Steel Tongs" },
  { id: 39, name: "Butcher", race: "Human", weapon: "Cleaver (as axe)", damage: "1d6", tradeGood: "Side of Beef" },
  { id: 40, name: "Caravan Guard", race: "Human", weapon: "Short Sword", damage: "1d6", tradeGood: "Linen, 1 Yard" },
  { id: 41, name: "Cheesemaker", race: "Human", weapon: "Cudgel (as Staff)", damage: "1d4", tradeGood: "Stinky Cheese" },
  { id: 42, name: "Cobbler", race: "Human", weapon: "Awl (as Dagger)", damage: "1d4", tradeGood: "Shoehorn" },
  { id: 43, name: "Confidence Artist", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "Quality Cloak" },
  { id: 44, name: "Cooper", race: "Human", weapon: "Crowbar (as Club)", damage: "1d4", tradeGood: "Barrel" },
  { id: 45, name: "Costermonger", race: "Human", weapon: "Knife (as Dagger)", damage: "1d4", tradeGood: "Fruit" },
  { id: 46, name: "Cutpurse", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "Small Chest" },
  { id: 47, name: "Ditchdigger", race: "Human", weapon: "Shovel (as Staff)", damage: "1d4", tradeGood: "Fine Dirt, 1 lbs." },
  { id: 48, name: "Farmer Potato", race: "Human", weapon: "Pitchfork (as Spear)", damage: "1d8", tradeGood: "Livestock (see notes)" },
  { id: 49, name: "Farmer Wheat", race: "Human", weapon: "Pitchfork (as Spear)", damage: "1d8", tradeGood: "Livestock (see notes)" },
  { id: 50, name: "Farmer Turnip", race: "Human", weapon: "Pitchfork (as Spear)", damage: "1d8", tradeGood: "Livestock (see notes)" },
  { id: 51, name: "Farmer Corn", race: "Human", weapon: "Pitchfork (as Spear)", damage: "1d8", tradeGood: "Livestock (see notes)" },
  { id: 52, name: "Farmer Rice", race: "Human", weapon: "Pitchfork (as Spear)", damage: "1d8", tradeGood: "Livestock (see notes)" },
  { id: 53, name: "Farmer Parsnip", race: "Human", weapon: "Pitchfork (as Spear)", damage: "1d8", tradeGood: "Livestock (see notes)" },
  { id: 54, name: "Farmer Radish", race: "Human", weapon: "Pitchfork (as Spear)", damage: "1d8", tradeGood: "Livestock (see notes)" },
  { id: 55, name: "Farmer Rutabaga", race: "Human", weapon: "Pitchfork (as Spear)", damage: "1d8", tradeGood: "Livestock (see notes)" },
  { id: 56, name: "Farmer Turnip", race: "Human", weapon: "Pitchfork (as Spear)", damage: "1d8", tradeGood: "Livestock (see notes)" }, // Duplicate from PHP
  { id: 57, name: "Fortune Teller", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "Tarot Deck" },
  { id: 58, name: "Gambler", race: "Human", weapon: "Club", damage: "1d4", tradeGood: "Dice" },
  { id: 59, name: "Gong Farmer", race: "Human", weapon: "Trowel (as Dagger)", damage: "1d4", tradeGood: "Sack of Night Soil" },
  { id: 60, name: "Ditcher", race: "Human", weapon: "Shovel (as Staff)", damage: "1d4", tradeGood: "Trowel (as Dagger)" },
  { id: 61, name: "Grave Digger", race: "Human", weapon: "Shovel (as Staff)", damage: "1d4", tradeGood: "Trowel (as Dagger)" },
  { id: 62, name: "Guild Beggar", race: "Human", weapon: "Sling", damage: "1d4", tradeGood: "Crutches" },
  { id: 63, name: "Beggar", race: "Human", weapon: "Sling", damage: "1d4", tradeGood: "Crutches" },
  { id: 64, name: "Healer", race: "Human", weapon: "Club", damage: "1d4", tradeGood: "Holy Water, 1 Vial" },
  { id: 65, name: "Herbalist", race: "Human", weapon: "Sling", damage: "1d4", tradeGood: "Herbs, 1 lbs." },
  { id: 66, name: "Herder", race: "Human", weapon: "Staff", damage: "1d4", tradeGood: "Herding Dog" },
  { id: 67, name: "Hunter", race: "Human", weapon: "Short Bow", damage: "1d6", tradeGood: "Deer Pelt" },
  { id: 68, name: "Huntsman", race: "Human", weapon: "Short Bow", damage: "1d6", tradeGood: "Deer Pelt" },
  { id: 69, name: "Indentured Servant", race: "Human", weapon: "Staff", damage: "1d4", tradeGood: "Locket" },
  { id: 70, name: "Jester", race: "Human", weapon: "Dart", damage: "1d4", tradeGood: "Silk Cloths" },
  { id: 71, name: "Jeweler", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "Gem worth 20 gp" },
  { id: 72, name: "Locksmith", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "Fine Tools" },
  { id: 73, name: "Mendicant", race: "Human", weapon: "Club", damage: "1d4", tradeGood: "Cheese Dip" },
  { id: 74, name: "Locksmith", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "Fine Tools" }, // Duplicate from PHP
  { id: 75, name: "Merchant", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "" },
  { id: 76, name: "Miller/Baker", race: "Human", weapon: "Club", damage: "1d4", tradeGood: "Flour, 1 lbs." },
  { id: 77, name: "Minstrel", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "Ukulele" },
  { id: 78, name: "Noble", race: "Human", weapon: "Longsword", damage: "1d8", tradeGood: "Gold Ring worth 10 gp" },
  { id: 79, name: "Orphan", race: "Human", weapon: "Club", damage: "1d4", tradeGood: "Rag Doll" },
  { id: 80, name: "Ostler", race: "Human", weapon: "Staff", damage: "1d4", tradeGood: "Bridle" },
  { id: 81, name: "Rope Maker", race: "Human", weapon: "Knife (as Dagger)", damage: "1d4", tradeGood: "Rope, 100'" },
  { id: 82, name: "Scribe", race: "Human", weapon: "Dart", damage: "1d4", tradeGood: "Parchment, 10 sheets" },
  { id: 83, name: "Shaman", race: "Human", weapon: "Mace", damage: "1d6", tradeGood: "Herbs, 1 lbs." },
  { id: 84, name: "Slave", race: "Human", weapon: "Club", damage: "1d4", tradeGood: "Strange-looking Rock" },
  { id: 85, name: "Smuggler", race: "Human", weapon: "Sling", damage: "1d4", tradeGood: "Waterproof Sack" },
  { id: 86, name: "Squire", race: "Human", weapon: "Longsword", damage: "1d8", tradeGood: "Steel Helmet" },
  { id: 87, name: "Herald", race: "Human", weapon: "Longsword", damage: "1d8", tradeGood: "Steel Helmet" },
  { id: 88, name: "Tax Collector", race: "Human", weapon: "Longsword", damage: "1d8", tradeGood: "" },
  { id: 89, name: "Trapper", race: "Human", weapon: "Sling", damage: "1d4", tradeGood: "Badger Pelt" },
  { id: 90, name: "Molecatcher", race: "Human", weapon: "Sling", damage: "1d4", tradeGood: "Mole Pelt" },
  { id: 91, name: "Urchin", race: "Human", weapon: "Stick (as Club)", damage: "1d4", tradeGood: "Begging Bowl" },
  { id: 92, name: "Wainwright", race: "Human", weapon: "Club", damage: "1d4", tradeGood: "Push Cart (see notes)" },
  { id: 93, name: "Weaver", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "Fine Suit of Clothes" },
  { id: 94, name: "Wizard's Apprentice", race: "Human", weapon: "Dagger", damage: "1d4", tradeGood: "Black Grimoire" },
  { id: 95, name: "Woodcutter", race: "Human", weapon: "Hand Axe", damage: "1d6", tradeGood: "Bundle of Wood" },
  { id: 96, name: "Woodmonger", race: "Human", weapon: "Hand Axe", damage: "1d6", tradeGood: "Bundle of Wood" },
  { id: 97, name: "Wood Seller", race: "Human", weapon: "Hand Axe", damage: "1d6", tradeGood: "Bundle of Wood" },
  { id: 98, name: "Mercenary", race: "Human", weapon: "Longsword", damage: "1d8", tradeGood: "" },
  { id: 99, name: "Outlaw", race: "Human", weapon: "Short Sword", damage: "1d6", tradeGood: "" },
  { id: 100, name: "Soldier", race: "Human", weapon: "Spear", damage: "1d8", tradeGood: "" }
];